services:
  - type: web
    name: productivity-app
    runtime: node
    domains:
      - donezo.duckdns.org
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 5000
      - key: CORS_ORIGIN
        value: https://donezo.duckdns.org,https://taskflow-xmum.onrender.com
    healthCheckPath: /api/health
